# Generated by Django 4.2.5 on 2024-04-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField(null=True)),
                ('intensity', models.IntegerField(max_length=100, null=True)),
                ('sector', models.CharField(max_length=100, null=True)),
                ('topic', models.CharField(max_length=100, null=True)),
                ('insight', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('start_year', models.IntegerField(null=True)),
                ('impact', models.CharField(max_length=100, null=True)),
                ('relevance', models.IntegerField(max_length=100, null=True)),
                ('pestle', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('likelihood', models.IntegerField(max_length=100, null=True)),
            ],
        ),
    ]
